language:
        - ruby

sudo : required

branches:
    only:
        - master

install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -y
    - sudo apt-get install texlive-latex-extra -y 
    - sudo apt-get install texlive-luatex -y
    - sudo apt-get install texlive-fonts-extra -y
    - sudo apt-get install cm-super -y
    - sudo apt-get install texlive-bibtex-extra -y
    - sudo apt-get install latexmk -y
    - sudo apt-get install tex4ht -y
    - sudo apt-get install texlive-fonts-recommended  -y
    - wget http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
    - sudo texlua install-getnonfreefonts
    - sudo getnonfreefonts-sys garamond

before_script:
    - sudo cp -fr RR/Glossario/res/glossaries /usr/share/texmf-texlive/tex/latex/
    - sudo cp -fr RR/Glossario/res/glossaries-italian/ /usr/share/texmf-texlive/tex/latex/

script:
    - cd RR/NormeDiProgetto/ && latexmk -pdflatex='pdflatex -interaction=nonstopmode' -pdf && cd -
    - cd RR/StudioDiFattibilita/ && latexmk -pdflatex='pdflatex -interaction=nonstopmode' -pdf && cd -
    - cd RR/PianoDiQualifica/ && latexmk -pdflatex='pdflatex -interaction=nonstopmode' -pdf && cd -
    - cd RR/LetteraDiPresentazione/ && latexmk -pdflatex='pdflatex -interaction=nonstopmode' -pdf && cd -

after_success:
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git clone --branch=gh-pages https://${GH_TOKEN}@github.com/bugbusterswe/documentation travis-build
    - cd travis-build/
    - mkdir -p build/
    - cd build/
    - cp -f $HOME/build/BugBusterSWE/documentation/RR/NormeDiProgetto/main.pdf .
    - mv main.pdf NormeDiProgetto_lastest.pdf
    - cp -f $HOME/build/BugBusterSWE/documentation/RR/StudioDiFattibilita/main.pdf .
    - mv main.pdf StudioDiFattibilita_lastest.pdf
    - cp -f $HOME/build/BugBusterSWE/documentation/RR/PianoDiQualifica/main.pdf .
    - mv main.pdf PianoDiQualifica_lastest.pdf
    - cp -f $HOME/build/BugBusterSWE/documentation/RR/LetteraDiPresentazione/main.pdf .
    - mv main.pdf LetteraDiPresentazione_lastest.pdf
    - git add NormeDiProgetto_lastest.pdf StudioDiFattibilita_lastest.pdf PianoDiQualifica_lastest.pdf LetteraDiPresentazione_lastest.pdf
    - git commit -m "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
    - git push -f origin gh-pages
