branches:
    only:
        - davide/feat/travisCI

install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -y
    - sudo apt-get install texlive-latex-extra -y 
    - sudo apt-get install texlive-luatex -y
    - sudo apt-get install texlive-fonts-extra -y
    - sudo apt-get install cm-super -y
    - sudo apt-get install texlive-bibtex-extra -y
    - sudo apt-get install latexmk -y
    - sudo apt-get install tex4ht -y
    - wget http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
    - sudo texlua install-getnonfreefonts
    - sudo getnonfreefonts-sys garamond

script:
    - cd RR/NormeDiProgetto/ && latexmk -pdflatex='pdflatex -interaction=nonstopmode' -pdf && cd -

after_success:
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/bugbusterswe/documentation travis-build
    - cd travis-build/
    - mkdir -p build/
    - cd build/
    - ls -lR
    - cp -f $HOME/build/BugBusterSWE/documentation/main.pdf .
    - git add main.pdf
    - git commit -m "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
    - git push -fq origin gh-pages > /dev/null


#    - gem install travis
#    - travis restart -r johnfoster-pge-utexas/johnfoster-pge-utexas.github.io --token ${TRAVIS_TOKEN} --skip-completion-check